version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - /app/node_modules
      - .:/app
    command: npm run develop -- --host 0.0.0.0
    environment:
      - NODE_ENV=development