# .github/workflows/push.yml
name: PR-Check

# On every pull request
on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  PR-Check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: https://registry.npmjs.org/
      - name: Build Check
        run: |
          npm install
          npm run build
